name: Daily Faceit Police

on:
  schedule:
    # 17:00 UTC varje dag
    - cron: "0 17 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --configuration Release
        env:
          FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MESSAGE_ID: ${{ vars.DISCORD_MESSAGE_ID }}
          TILT_WATCH_MESSAGE_ID: ${{ vars.TILT_WATCH_MESSAGE_ID }}
          FACEIT_PLAYERS: ${{ vars.FACEIT_PLAYERS }}
